package application;


import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;


public class loginController implements Initializable{
	
	@FXML
	 private PasswordField passenger_pass;
	
    @FXML
    private TextField pass_id;
    
    @FXML
    private Button clbutton;
    
    @FXML
    private Button elbutton;

    @FXML
    private TextField emp_id;

    @FXML
    private PasswordField emp_pass;
    
    
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
	
    
    
	//----------------------------login to register------------------------------------
	@FXML
	public void OnClicked(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent new_user_parent = FXMLLoader.load(getClass().getResource("Register.fxml"));
		Scene new_user_scene = new Scene(new_user_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(new_user_scene);
		app_stage.show();
		
	}
	
	//-------------------------login to customer login-----------------------------------
	
	
	@FXML
	public void cl_signin(ActionEvent event) throws IOException, SQLException {
//		TODO Autogenerated
		
		
		 Window owner = clbutton.getScene().getWindow();

	        System.out.println(pass_id.getText());
	        System.out.println(passenger_pass.getText());

	        if (pass_id.getText().isEmpty()) {
	            showAlert(Alert.AlertType.ERROR, owner, "Form Error!",
	                "Please enter your user id");
	            return;
	        }
	        if (passenger_pass.getText().isEmpty()) {
	            showAlert(Alert.AlertType.ERROR, owner, "Form Error!",
	                "Please enter a password");
	            return;
	        }

	        String user = pass_id.getText();
	        String password = passenger_pass.getText();

	        JdbcDao jdbcDao = new JdbcDao();
	        boolean flag = jdbcDao.validate(user, password);

	        if (!flag) {
	            infoBox("Please enter correct user id and Password", null, "Failed");
	        } else {
	            infoBox("Login Successful!", null, "Successful");
	            
	            Parent customer_login_parent = FXMLLoader.load(getClass().getResource("customer_login.fxml"));
	    		Scene customer_login_scene = new Scene(customer_login_parent);
	    		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	    		app_stage.setScene(customer_login_scene);
	    		app_stage.show();
	            
	        }	
	}
	

	
	public static void infoBox(String infoMessage, String headerText, String title) {
        Alert alert = new Alert(AlertType.CONFIRMATION);
        alert.setContentText(infoMessage);
        alert.setTitle(title);
        alert.setHeaderText(headerText);
        alert.showAndWait();
    }

	private static void showAlert(Alert.AlertType alertType, Window owner, String title, String message) {
        Alert alert = new Alert(alertType);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.initOwner(owner);
        alert.show();
    }


	
	
	//---------------------------login to employee login----------------------------------
	
	

	@FXML
	public void whenClicked(ActionEvent event) throws IOException, SQLException {
//		TODO Autogenerated

		
		 Window owner = elbutton.getScene().getWindow();

	        System.out.println(emp_id.getText());
	        System.out.println(emp_pass.getText());

	        if (emp_id.getText().isEmpty()) {
	            showAlertemp(Alert.AlertType.ERROR, owner, "Form Error!",
	                "Please enter your user id");
	            return;
	        }
	        if (emp_pass.getText().isEmpty()) {
	            showAlertemp(Alert.AlertType.ERROR, owner, "Form Error!",
	                "Please enter a password");
	            return;
	        }

	        String emp_user = emp_id.getText();
	        String emp_password = emp_pass.getText();

	        emplogindb emplogin = new emplogindb();
	        boolean flag = emplogin.validate(emp_user, emp_password);

	        if (!flag) {
	            infoBoxemp("Please enter correct User id and Password", null, "Failed");
	        } else {
	            infoBoxemp("Login Successful!", null, "Successfull");
	            Parent employee_login_parent = FXMLLoader.load(getClass().getResource("employee_login.fxml"));
	    		Scene employee_login_scene = new Scene(employee_login_parent);
	    		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	    		app_stage.setScene(employee_login_scene);
	    		app_stage.show();
	        }
	}
	
	public static void infoBoxemp(String infoMessage, String headerText, String title) {
        Alert alert = new Alert(AlertType.CONFIRMATION);
        alert.setContentText(infoMessage);
        alert.setTitle(title);
        alert.setHeaderText(headerText);
        alert.showAndWait();
    }

	private static void showAlertemp(Alert.AlertType alertType, Window owner, String title, String message) {
        Alert alert = new Alert(alertType);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.initOwner(owner);
        alert.show();
    }


	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	}
}
