package application;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;


public class RegisterController {

    @FXML
    private Button btn_submit_newuser;

    @FXML
    private TextField tf_gender;

    @FXML
    private TextField tf_age;
    
    @FXML
    private TextField tf_ticket_id;

    @FXML
    private TextField tf_dob;

    @FXML
    private TextField tf_email;

    @FXML
    private TextField tf_name;

    @FXML
    private PasswordField tf_new_password;

    @FXML
    private TextField tf_new_username;

    @FXML
    private TextField tf_phonenumber;

    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    


    //register to login
    @FXML
	public void submit(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent register_parent = FXMLLoader.load(getClass().getResource("login.fxml"));
		Scene register_scene = new Scene(register_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(register_scene);
		app_stage.show();
    }
	
    

    
    
    @FXML
	public void onclick(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent submit_parent = FXMLLoader.load(getClass().getResource("login.fxml"));
		Scene submit_scene = new Scene(submit_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(submit_scene);
		app_stage.show();
		
		System.out.println(tf_ticket_id.getText());
		System.out.println(tf_new_username.getText());
		System.out.println(tf_name.getText());
		System.out.println(tf_phonenumber.getText());
	    System.out.println(tf_age.getText());
	    System.out.println(tf_email.getText());
	    System.out.println(tf_new_password.getText());
	    System.out.println(tf_gender.getText());
	    
	    JOptionPane.showMessageDialog(null, "User Add successfully");
	    
	   
	   
	    newuser.newuserDatabase(tf_ticket_id.getText(), tf_new_username.getText(), tf_name.getText(), tf_phonenumber.getText(), tf_age.getText(), tf_email.getText(), tf_new_password.getText(), tf_gender.getText());
	    
		
	}
}
